artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  gdrive_file_id: 1XaNxpHP3XwDyKjEw-1wirLcgLqMRSsV-


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


