artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  gdrive_file_id: 1XaNxpHP3XwDyKjEw-1wirLcgLqMRSsV-
